#deploy stage:
#    image: alpine
#    stage: deploy
#    script:
#        - apk add --no-cache rsync openssh sshpass
#        - mkdir -p ~/.ssh
#        - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
#        - chmod 600 ~/.ssh/id_dsa
#        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
#        - sshpass -p "$DEV_PASS" ssh -p 2299 $DEV_USER@$DEV_HOST "cd $DEV_PATH_DEVELOPMENT && git pull https://$GIT_USER:$GIT_PASS@gitlab.com/apoonz/siresto.git dev"
#    only:
#        - dev
